[package]
name = "csv-to-md-table"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
clap = { version = "4.5.28", features = ["derive"] }
anyhow = "1.0.96"

[dev-dependencies]
tempfile = "3.3"
